[tool.briefcase]
project_name = "LanFund"
bundle = "com.lanfund"
version = "0.1"
url = "https://github.com/18801089096/fund"
license = "MIT"
author = "LanZz"
author_email = "test@example.com"  # 补上了这个
description = "A fund monitor app" # 补上了这个

[tool.briefcase.app.fundapp]
formal_name = "LanFund"
description = "A fund monitor app"
sources = ["src/fundapp"]
requires = [
    "flask>=2.0",
    "requests",
    "tabulate",
    "loguru",
    "python-dotenv",
    "flask-login"
]



[tool.briefcase.app.fundapp.macOS]
requires = ["std-nslog"]

[tool.briefcase.app.fundapp.iOS]
requires = ["std-nslog"]
