[tool.briefcase]
project_name = "LanFund"
bundle = "com.lanfund"
version = "0.1"
url = "https://github.com/18801089096/fund"
license = "MIT"
author = "LanZz"
author_email = "test@example.com"  # 补上了这个
description = "A fund monitor app" # 补上了这个

[tool.briefcase.app.fundapp]
formal_name = "LanFund"
description = "A fund monitor app"
sources = ["src/fundapp"]
requires = [
    "flask",
    "requests",
    "tabulate",
    "loguru",
    "python-dotenv",
    "flask-login",
    "werkzeug"
]
icon = "src/fundapp/static/1" # 尝试使用你的图标（可选，如果报错可以删掉这行）

[tool.briefcase.app.fundapp.macOS]
requires = ["std-nslog"]

[tool.briefcase.app.fundapp.iOS]
requires = ["std-nslog"]
